### ISSUE TITLE
PyInstaller Producing Broken Cloud Node Bundles

### ISSUE THREAD

**Issue by geedo0** [mit-ll/python-keylime#3]
# Environment
 * OS / version: Heads(For Executing Node Bundle)/Ubuntu 16.04(For building the bundle)
 * Processor architecture: x86_64
 * TPM Manufacturer: 
```
 tpm_version
  TPM 1.2 Version Info:
  Chip Version:        1.2.5.81
  Spec Level:          2
  Errata Revision:     3
  TPM Vendor ID:       WEC
  Vendor Specific data: 0000
  TPM Version:         01010000
  Manufacturer Info:   57454300
```
 * Keylime version: [Commit](https://github.com/mit-ll/python-keylime/commit/2e7716c1393116c8a39aa47989a0eecdfd07a3b2)

# Description 
Whenever I build the Keylime Node Tarball on this machine, it generates a bad version of the binary that doesn't launch successfully. I can successfully build a working cloud node on a different VM. This was a vanilla Ubuntu 16.04 VM setup just to run Keylime and DNSMasq so there's nothing particularly special about it. Seems to have something to do with PyInstaller.

## Expected behavior vs. actual behavior 
A working cloud node should be generated successfully on all machines.

## Steps to reproduce problem
1. Run the installer.sh script on the problematic node
1. Deploy cloud node onto Heads
1. Execute cloud node

# Relevant logs
![image](https://user-images.githubusercontent.com/7552310/29333755-fe9b740e-81d2-11e7-9457-90ff05247936.png)

**Comment by jetwhiz** [comment]
Hi @geedo0 -- it looks like this issue has been fixed in the pyinstaller repository, but has not yet been released as an official release (https://github.com/pyinstaller/pyinstaller/pull/2453) 

In the meantime, copying their hook file [PyInstaller/hooks/hook-Cryptodome.py](https://raw.githubusercontent.com/pyinstaller/pyinstaller/dacc07f49e2c22bba5473f4cb5b2a5194cdae5e1/PyInstaller/hooks/hook-Cryptodome.py) into your `PyInstaller/hooks/` directory (e.g.,`/usr/local/lib/python2.7/dist-packages/PyInstaller/hooks/` or `/usr/lib/python2.7/site-packages/PyInstaller/hooks/`) should solve this issue.

**Comment by nabilschear** [comment]
should we make a note of this in the readme?

**Comment by geedo0** [comment]
I can confirm that the workaround fixes this issue.
